### ISSUE TITLE
Rented Micromobility & Transit trips always begin immediately at departure time

### ISSUE THREAD

**Issue by broder22** [ibi-group/OpenTripPlanner#14]
##  Expected behavior
Trips begin only early enough to complete any necessary transfers (how Bike & Transit trips currently work)

## Observed behavior
Trips always begin immediately, sometimes causing very long waiting times at transfer points. This occurs on both my instance, and the trimet beta trip planner. This could be desirable since the floating vehicles may move at any point, but there are often many options nearby to replace it. It seems unlikely anyone would follow many of the itineraries as currently generated.

## Steps to reproduce the problem
Plan any trip using Rented Micromobility and Transit.

![image](https://user-images.githubusercontent.com/20190752/64228163-99687500-ceab-11e9-8865-6995779d9f7d.png)

![image](https://user-images.githubusercontent.com/20190752/64228272-ea786900-ceab-11e9-9523-cb84d76e214c.png)

https://betaplanner.trimet.org/map/#/?ui_activeSearch=mon9k5zqs&ui_activeItinerary=2&fromPlace=10%20NW%2012th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097209%3A%3A45.523307418747926%2C-122.68274638971185&toPlace=4216%20NE%2030th%20Ave%2C%20Portland%2C%20OR%2C%20USA%2097211%3A%3A45.55396771389642%2C-122.63454011976454&date=2019-09-03&time=19%3A41&arriveBy=false&mode=BUS%2CTRAM%2CRAIL%2CGONDOLA%2CMICROMOBILITY_RENT&showIntermediateStops=true&optimize=QUICK&maxWalkDistance=4828&maxEScooterDistance=4828&ignoreRealtimeUpdates=true&companies=BIRD%2CBOLT%2CLIME%2CRAZOR%2CSHARED%2CSPIN

**Comment by evansiroky** [comment]
Thanks for the report. I'll discuss this among my team members to see if we can allocate some time to fix.
