### ISSUE TITLE
Time and Mode: no trip plans (PATH_NOT_FOUND error) for trips that start more than 30 minutes prior to departure

### ISSUE THREAD

**Issue by fpurcell** [ibi-group/OpenTripPlanner#172]
## Expected behavior

Plan trips when a journey is possible w/in the maxJourneyDuration (say with a value of 6 hours) window.  So if let's say the agency has a TRAIN mode route with one trip each M-F at 3:45pm, and it is 10am on a Monday when a customer asks OTP for a depart after trip; the routing engine will return an itinerary for the request, using that first train trip that begins at 3:45pm.  If it is Saturday at 10am (or Monday at 5am), then the routing probably would not return a result because the first possible trip is too far in the future from the specified time, as specified by maxJourneyDuration (again set with a value of 6 hours).

## Observed behavior

The first afternoon train doesn't arrive until ~3:45pm at TIGARD TC.  When I request a trip (without the BUS mode) departing at 3pm starting from the TIGARD TC stop, I get a PATH_NOT_FOUND error:

http://maps8.trimet.org/otp_ct/plan?fromPlace=TIGARD_TC::45.430457,-122.771456&toPlace=SUNSET_TC::45.491320,-122.802537&mode=TRAM,RAIL,GONDOLA,WALK&time=3:00PM&date=06-06-2023

But if I bump the depart time to 3:30pm, or if I add BUS mode and use the 3pm depart time, I will get a valid itinerary:

http://maps8.trimet.org/otp_ct/plan?fromPlace=TIGARD_TC::45.430457,-122.771456&toPlace=SUNSET_TC::45.491320,-122.802537&mode=TRAM,RAIL,GONDOLA,WALK&time=3:30PM&date=06-06-2023

http://maps8.trimet.org/otp_ct/plan?fromPlace=TIGARD_TC::45.430457,-122.771456&toPlace=SUNSET_TC::45.491320,-122.802537&mode=BUS,TRAM,RAIL,GONDOLA,WALK&time=3:00PM&date=06-06-2023

## Version of OTP used (exact commit hash or JAR name)
d64f319a8b5215651349953eb4f9450ad01b1bf1

## Data sets in use (links to GTFS and OSM PBF files)
https://maps8.trimet.org/ct/

## Router config and graph build config JSON
https://maps8.trimet.org/ct/router-config.json

## Steps to reproduce the problem

Curl the following URLs.  
http://maps8.trimet.org/otp_ct/plan?fromPlace=TIGARD_TC::45.430457,-122.771456&toPlace=SUNSET_TC::45.491320,-122.802537&mode=TRAM,RAIL,GONDOLA,WALK&time=3:00PM&date=06-06-2023

http://maps8.trimet.org/otp_ct/plan?fromPlace=TIGARD_TC::45.430457,-122.771456&toPlace=SUNSET_TC::45.491320,-122.802537&mode=BUS,TRAM,RAIL,GONDOLA,WALK&time=3:00PM&date=06-06-2023

**Comment by miles-grant-ibigroup** [comment]
Thanks for opening this! Would you possibly be able to open the ticket in the upstream OTP repo? I've thought about it and I think this issue tracker should be for OTP1 only.

https://github.com/opentripplanner/OpenTripPlanner/issues

**Comment by fpurcell** [comment]
https://github.com/opentripplanner/OpenTripPlanner/issues/5195
